I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 94, in script
    show Hans Talking at left
Exception: Image 'Hans' does not accept attributes 'Talking'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 94, in script
    show Hans Talking at left
  File "/Applications/renpy-8.2.0-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Applications/renpy-8.2.0-sdk/renpy/ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "/Applications/renpy-8.2.0-sdk/renpy/exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Applications/renpy-8.2.0-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/Applications/renpy-8.2.0-sdk/renpy/display/displayable.py", line 246, in _duplicate
    args.extraneous()
  File "/Applications/renpy-8.2.0-sdk/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'Hans' does not accept attributes 'Talking'.

macOS-10.15.7-x86_64-i386-64bit x86_64
Ren'Py 8.2.0.24012702
Attack Berlin v0.2 0.2
Sun Feb  4 18:43:23 2024
